#!/bin/bash
# RAAF Backup Cron Installer
# Installs a daily backup cron job at 12:30 AM EST
# Pauses watch_applicants during backup, restarts after
#
# Usage: ./install_backup_cron.sh [--target local|gdrive] [OPTIONS]
#   Options are passed through to backup.sh

set -euo pipefail

RAAF_DIR="/home/alonsop/RAAF"
BACKUP_SCRIPT="$RAAF_DIR/backup.sh"
BACKUP_WRAPPER="$RAAF_DIR/run_backup.sh"
CRON_MARKER="# RAAF-BACKUP"

# Default backup args (can be overridden via command line)
BACKUP_ARGS="--target gdrive --gdrive-remote raaf-backup:RAAF-Backups --quiet"
if [ $# -gt 0 ]; then
    BACKUP_ARGS="$*"
fi

echo "=============================================="
echo "RAAF Backup Cron Installer"
echo "=============================================="
echo ""

# Check prerequisites
echo "[1/4] Checking prerequisites..."

if [ ! -f "$BACKUP_SCRIPT" ]; then
    echo "ERROR: backup.sh not found at $BACKUP_SCRIPT"
    exit 1
fi

# Check if rclone is needed and available
if echo "$BACKUP_ARGS" | grep -q "gdrive"; then
    if ! command -v rclone &>/dev/null; then
        echo ""
        echo "WARNING: rclone is not installed."
        echo "Install it with: sudo apt install rclone"
        echo "Then configure a remote: rclone config"
        echo ""
        echo "Steps to configure Google Drive remote:"
        echo "  1. Run: rclone config"
        echo "  2. Choose 'n' for new remote"
        echo "  3. Name it: raaf-backup"
        echo "  4. Choose 'Google Drive' as storage type"
        echo "  5. Follow the OAuth prompts"
        echo "  6. Re-run this installer after setup"
        exit 1
    fi

    REMOTE_NAME=$(echo "$BACKUP_ARGS" | grep -oP '(?<=--gdrive-remote )\S+' | cut -d: -f1)
    if [ -n "$REMOTE_NAME" ] && ! rclone listremotes 2>/dev/null | grep -q "^${REMOTE_NAME}:$"; then
        echo ""
        echo "WARNING: rclone remote '$REMOTE_NAME' is not configured."
        echo "Run: rclone config"
        echo "Create a remote named '$REMOTE_NAME' pointing to Google Drive."
        exit 1
    fi
fi

echo "Prerequisites OK"

# Create the backup wrapper script (stops watcher, runs backup, restarts watcher)
echo "[2/4] Creating backup wrapper script..."

cat > "$BACKUP_WRAPPER" << 'WRAPPER_EOF'
#!/bin/bash
# RAAF Backup Wrapper - stops watch_applicants, runs backup, restarts watcher
# Auto-generated by install_backup_cron.sh

RAAF_DIR="/home/alonsop/RAAF"
LOG_FILE="$RAAF_DIR/logs/backup.log"
WATCHER_WAS_RUNNING=false

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

# Stop watch_applicants if running
WATCHER_PID=$(pgrep -f "watch_applicants.py" || true)
if [ -n "$WATCHER_PID" ]; then
    WATCHER_WAS_RUNNING=true
    log "Stopping watch_applicants (PID: $WATCHER_PID) for backup"
    kill "$WATCHER_PID" 2>/dev/null || true
    sleep 2
    # Force kill if still running
    if kill -0 "$WATCHER_PID" 2>/dev/null; then
        kill -9 "$WATCHER_PID" 2>/dev/null || true
    fi
    log "watch_applicants stopped"
fi

# Run backup
WRAPPER_EOF

# Append the backup command with the configured args
echo "$BACKUP_SCRIPT $BACKUP_ARGS" >> "$BACKUP_WRAPPER"

cat >> "$BACKUP_WRAPPER" << 'WRAPPER_EOF'
BACKUP_EXIT=$?

# Restart watch_applicants if it was running
if [ "$WATCHER_WAS_RUNNING" = true ]; then
    log "Restarting watch_applicants"
    cd "$RAAF_DIR"
    nohup python3 scripts/pcr/watch_applicants.py --interval 15 >> "$RAAF_DIR/logs/watch_applicants.log" 2>&1 &
    log "watch_applicants restarted (PID: $!)"
fi

exit $BACKUP_EXIT
WRAPPER_EOF

chmod +x "$BACKUP_WRAPPER"
echo "Wrapper created: $BACKUP_WRAPPER"

# Set permissions
echo "[3/4] Setting permissions..."
chmod +x "$BACKUP_SCRIPT"
echo "Scripts are executable"

# Install cron job
echo "[4/4] Installing cron job..."

# Remove existing RAAF backup cron entry if present
EXISTING_CRON=$(crontab -l 2>/dev/null || true)
NEW_CRON=$(echo "$EXISTING_CRON" | grep -v "$CRON_MARKER" || true)

# Add new cron entry: 12:30 AM daily
CRON_ENTRY="30 0 * * * $BACKUP_WRAPPER $CRON_MARKER"
NEW_CRON=$(printf '%s\n%s\n' "$NEW_CRON" "$CRON_ENTRY")

echo "$NEW_CRON" | crontab -
echo "Cron job installed: daily at 12:30 AM"

echo ""
echo "=============================================="
echo "Installation Complete!"
echo "=============================================="
echo ""
echo "Backup schedule: Daily at 12:30 AM"
echo "Backup command:  $BACKUP_SCRIPT $BACKUP_ARGS"
echo "Wrapper script:  $BACKUP_WRAPPER"
echo "Log file:        $RAAF_DIR/logs/backup.log"
echo ""
echo "The backup will:"
echo "  1. Stop watch_applicants (if running)"
echo "  2. Create a timestamped archive of clients/, config/, archive/"
echo "  3. Upload/save to the configured target"
echo "  4. Restart watch_applicants"
echo "  5. Keep the last $((30)) backups, delete older ones"
echo ""
echo "To verify: crontab -l | grep RAAF"
echo "To test:   $BACKUP_WRAPPER"
echo ""
